### ISSUE TITLE
rights, rightsHolder and datasetName

### ISSUE THREAD

**Issue by LienReyserhove** [trias-project/wrims-checklist#10]
These fields are empty for the moment. I suggest the following:

* `rights`: CC0 license (http://creativecommons.org/publicdomain/zero/1.0/)
* `datasetName`: "World Register of Introduced Marine Species (WRIMS)

Then, for `rightsHolder`, I'm not quite sure, this could be 
- VLIZ
- ISSG
- www.marinespecies.org
- ...

i.e. who holds the "WRIMS rights"?

**Comment by bart-v** [comment]
No, they are not empty, your system fails to read a Darwin Core file properly.
Please use meta.xml:
`<field index="26" default="http://creativecommons.org/licenses/by/4.0/" term="http://purl.org/dc/terms/rights"/>`
`<field index="27" default="WoRMS Editorial Board" term="http://purl.org/dc/terms/rightsHolder"/>`
`<field index="28" default="WoRMS WRIMS" term="http://rs.tdwg.org/dwc/terms/datasetName"/>`

**Comment by peterdesmet** [comment]
@bart-v thanks for the info. Note: the term ”rights” has been deprecated in Darwin Core in favour of “license”: 	http://purl.org/dc/terms/license. Can you update this in the next version of the archive?

**Comment by bart-v** [comment]
Yes, the next version will have "license"
