### ISSUE TITLE
countryCode

### ISSUE THREAD

**Issue by LienReyserhove** [trias-project/wrims-checklist#11]
To select the belgian species, we select on `countryCode` = `BE`
This field is absent in WRIMS. Is it possible to populate this field with an [ISO3166 Code](https://www.iso.org/iso-3166-country-codes.html)?

**Comment by bart-v** [comment]
Well, there is Country='Belgium' I can't imagine there is an issue with that...

**Comment by peterdesmet** [comment]
@bart-v there is no `country` field in the distribution extension: http://rs.gbif.org/extension/gbif/1.0/distribution.xml. There is:

- `locationID`: A code for the named area this distributon record is about.
- `locality`: The verbatim name of the area this distributon record is about.
- `countryCode`: ISO3166 alpha 2 (3 is permissable) country codes the area belongs to or as an alternative for a lcoationID if the area is a country.

The literal value `Belgium` could be provided in `locality` if there is no more precise locality information, but to indicate that the locality is in Belgium, please use `countryCode=BE` using the https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2 standard.

**Comment by LienReyserhove** [comment]
Indeed. This field of `countryCode` is really important for us as this is the selection criterion to filter out the belgian species for the unified checklist. This process is automated, so absence of this field implies that non of the WRIMS species will be integrated in the unified checklist.

**Comment by peterdesmet** [comment]
Note: there are ways around it (involves _us_ interpreting `locality` information), but indeed, having `countryCode=BE` would be much more efficient.

**Comment by bart-v** [comment]
This has been implemented and will be available in the next export (2019-04-01)
