### ISSUE TITLE
eventDate

### ISSUE THREAD

**Issue by LienReyserhove** [trias-project/wrims-checklist#12]
In the unified checklist, we select on date information contained in the field `eventDate`. This field is lacking in WRIMS at this point. Is it possible to populate this field by combining information in `startDayOfYear` and `endDayOfYear`? We need it to be in this format: `yyyy/yyyy`.

In several cases, I see that `startDayOfYear` or `endDayOfYear` is lacking. _One way_ to deal with this is:
- `endDayOfYear` lacking: use the year of the last update of WRIMS
- `startDayOfYear` is lacking: use the same year as in `endDayOfYear`

**Comment by bart-v** [comment]
It seems like we messed up there:
"startDayOfYear" = The earliest **ordinal day** of the year on which the distribution record is valid
So we used this field in a completely wrong way :)

So, we will remove these fields and replace them with "eventDate"
Will be available in the next update

Populating fields with the latest update date of WRIMS is wrong: empty does not mean that the last update is the correct date, it could be that the species is no longer occurring there or similar. Empty should stay empty in my opinion.
