### ISSUE TITLE
acceptedNameUsageID and parentNameUsageID

### ISSUE THREAD

**Issue by LienReyserhove** [trias-project/wrims-checklist#14]
In line with the [earlier discussion](https://github.com/trias-project/wrims-checklist/issues/5) about the content of `taxonID`, I suggest to use long aphiaID (`urn:lsid:marinespecies.org:taxname:`) for the fields `acceptedNameUsageID` and `parentNameUsageID` instead of the short (integer) version.

**Comment by bart-v** [comment]
This has been implemented and will be available in the next export (2019-04-01)
