### ISSUE TITLE
namePublishedInID

### ISSUE THREAD

**Issue by LienReyserhove** [trias-project/wrims-checklist#15]
This field refers to the doi of the publication, but lacks the protocol and domain name (`https://doi.org/`). I suggest to add this information. The publications will be easier to access.

Thus:
`10.5962/bhl.title.2081` --> `https://doi.org/10.5962/bhl.title.2081`

**Comment by bart-v** [comment]
Sigh... this has been implemented and will be available in the next export (2019-04-01)
