### ISSUE TITLE
Some terms in the description extension need special attention

### ISSUE THREAD

**Issue by LienReyserhove** [trias-project/wrims-checklist#17]
The description extension contains information related to the following variables, specified in `type`:

type | records
|:---|----------:|
Introduced species abundance	|	317
Introduced species impact	|	726
Introduced species management	|	28
Introduced species remark	|	383
Introduced species vector dispersal	|	1969
Introduced species population trend | 137
Distribution |	2
Introduced species population |	6
Introduction |	1
Synonymy |	1
Taxonomic remark |	2
Type locality |	1

Some of these variables need special attention:

**Distribution:**

type 		|description            		|taxonID									 	 
|:------------------------------|-------------------------------------------------------|-------------------
distribution					|Native and introduced ranges							|urn:lsid:marinespecies.org:taxname:236666 		

As this concern only 2 records (1 taxon with two references), I wonder if this is correct?

**introduced species population:**

type 		|description            		|taxonID									 	 
|:------------------------------|-------------------------------------------------------|-------------------
Introduced species population   |in Canary Islands (...): Increasing 					|	urn:lsid:marinespecies.org:taxname:107458	
Introduced species population   |in Azores part (...): Increasing 						|	urn:lsid:marinespecies.org:taxname:107458
Introduced species population   |in United States (Nation):	Increasing 					| urn:lsid:marinespecies.org:taxname:140657
Introduced species population   |in Celtic Sea (IHO Sea Area):	Increasing 				| urn:lsid:marinespecies.org:taxname:152356
Introduced species population   |in Australia (Nation):	Increasing 						| urn:lsid:marinespecies.org:taxname:254497
Introduced species population   |in Hawaiian part of (...): Increasing 					|urn:lsid:marinespecies.org:taxname:380387

This information is very similar as in `introduced species population trend`. Probably an error?

**type locality**

type 		|description            		|taxonID									 	 
|:------------------------------|-------------------------------------------------------|-------------------
Type locality					|Persian Gulf 											| urn:lsid:marinespecies.org:taxname:141572

As this concern only 1 record, I wonder if this is correct? 

**introduction**

type 		|description            		|taxonID									 	 
|:------------------------------|-------------------------------------------------------|-------------------
Introduction					|Both shipping activities and natural dispersion (...) 	| urn:lsid:marinespecies.org:taxname:140416

Is a vector and should be under `Introduced species vector dispersal`

**Comment by bart-v** [comment]
All of these are content issues: all fixed.
Available on the website now, and in the next export 2019-05-01
