### ISSUE TITLE
select Belgian locations

### ISSUE THREAD

**Issue by LienReyserhove** [trias-project/wrims-checklist#3]
WRIMS containes data about 1376 unique localities. We need to filter out the Belgian ones. However, filtering on localities containing "belg-" is not sufficient. 

An example of some localities:
- De Panne
- Koksijde
- Zeebrugge
- Spuikom
- ...

It's a tedious job to check them all. However, for each, we have coordinate information available, although not in the distribution extension but on http://marineregions.org. 
For instance, this is the information for Spuikom: http://marineregions.org/mrgid/5477

Maybe we could use the coordinate information to filter out the Belgian localities?

**Comment by peterdesmet** [comment]
As long as:

- Each record in the distribution extension has `countryCode` populated
- Ideally, each location is its own record in the distribution extension (and thus not `De Panne, Koksijde, ...` concatenated).

We will be able to filter on filter on non-native distributions for belgium, using:

* countryCode = BE
* establishmentMeans = introduced
* occurrenceStatus = present

**Comment by LienReyserhove** [comment]
Countrycode is not provided yet. So this still needs to be done.
To avoid that someone needs to interpret all the localities, I made the suggestion of using the coordinates. But if you know the data it shouldn't be much effort to just add the countrycode I assume.

**Comment by bart-v** [comment]
We (WRIMS/Aphia) can automatically populate the field "countryCode" via the marineregions.org gazetteer (all localities have a hierarchy).
There is no need to do this manually.

**Comment by LienReyserhove** [comment]
Thank you for this! When could you provide us with this update? 
If I have this information, I can have a better idea which values for `occurrenceStatus`, `invasion stage` and `establishmentMeans `we need to integrate (see #2 )

**Comment by bart-v** [comment]
The next update (2018-05-01) should have it.

**Comment by LienReyserhove** [comment]
Thanks for the update!
There are now 963 records for Belgium. 
One question: a large majority of the new `country` field remains unpopulated. E.g. taxonID 100872 in the distribution extension has `locality = North Sea`. Obviously, this species does not occur exclusively in Belgium, but what to do with it? Do we only integrate species for which have have country information or do we broaden the scope (which will make our task a lot more complex)...
I suggest the first option...

**Comment by bart-v** [comment]
I think you will need to go through all distinct localities and see which ones can be attributed to Belgium sensu lato.

You can try to use the marineregions.org REST API to do this (semi)automatically, but I'm afraid this will not work out well.

**Comment by peterdesmet** [comment]
> Do we only integrate species for which have have country information ...

Yes, that is the safest option and we'll see how far we get with that.

**Comment by LienReyserhove** [comment]
Decided to go for option one
