### ISSUE TITLE
species profile - isExtinct

### ISSUE THREAD

**Issue by LienReyserhove** [trias-project/wrims-checklist#4]
In the species profile extension, `isExtinct` can have three different values: NA, 0 or 1.
83,6 % of all species has `NA` for `isExtinct`. 
Does this mean that we don't know if they are still present in the specific region? Or if this hasn't been verified? Or...? i.e.: what is the difference with `isExtinct` = 0?

**Comment by bart-v** [comment]
NA means we simple don't know, or experts have not populated that field, yet.
But for TriAS you can safely assume that NA means Extinct = 0
It is a species property, so it's not related to the specific regions at all.

We have a number of editors who focus on fossil taxa, and they will always put Extinct = 1
