### ISSUE TITLE
taxonID

### ISSUE THREAD

**Issue by LienReyserhove** [trias-project/wrims-checklist#5]
For `taxonID` a globally unique ID is preferred. Right now, `taxonID` contains values ranging from 0 - 1055693. Although the use of globally unique identifiers is not mandatory, we strongly encourage it. For TrIAS, we use the combination of the dataset shortname + taxon + a random generated hash based on the scientific name of the species (see also https://github.com/trias-project/alien-plants-belgium/issues/44).

E.g.: alien-plants-belgium: taxon: 5c33253debbe5777c0499b5c4d76b6e4 for `Actinidia deliciosa (Chevalier)` in the Manual of Alien Plants.

If I remember it correctly, this method was not an option for the WRIMS checklist. Al alternative would be to use the values currently contained in `scientificNameID` for `taxonID`, which is a globally unique identifier for an aphiaID. Thus, the current `taxonID` should be replaced by the values in `scientificNameID` to make it globally unique.

**Comment by bart-v** [comment]
Yes, please you can use the scientificNameID field, 
No need to invent yet another identifier :)

A hash based on the name has been discussed many times in GNA/GNI/ contexts.
This is not workable in practice, and just adds more rubbish to the mess.

It seems this project just keeps trying to invent the wheel...
urn:lsid:ipni.org:names:913605-1 is the identifier you should use for Actinidia deliciosa (Chevalier).

**Comment by qgroom** [comment]
The taxonID is a globally unique value for the taxon record in the dataset. The scientificNameID is an ID to the "_An identifier for the nomenclatural (not taxonomic) details of a scientific name._". Therefore we use this as the scientificNameID http://ipni.org/urn:lsid:ipni.org:names:913605-1, as you suggest, but if we used this as the taxonID it would make a duplicate globally unique ID. Or am I missing something.

**Comment by bart-v** [comment]
Yes, ideally taxonID and scientificNameID should be different....

But, the hash is just a proxy for the name.
Multiple scientificNameIDs that represent the same taxon will NOT have the same taxonID.
So, it's just a more obscure representation of the scientificNameID...

So, then it's maybe better not use taxonID after all, or just to duplicate the scientificNameID, in my opinion.

**Comment by LienReyserhove** [comment]
Leaving taxonID out is not an option, as this is an mandatory field in the taxon core. We also need taxonID as GBIF uses these values to generate their taxonKeys (see https://github.com/trias-project/alien-plants-belgium/issues/44#issuecomment-348428907). 

I think the most important thing is that taxonID remains as stable as possible and that it is not duplicated for different species. 

However, I still prefer the use of a hash as we use this approach for all our datasets. Also, the taxonID is an identifier for the taxon record **in the dataset** , while scientificNameID is a unique identifier for the species itself. So for that reason, imo, they should differ.

But, if we don't find a consensus on this, than I think using scientificNameID is the best solution, as this is a stable, unique identifier. I don't think that duplicating these ID's between fields is a big problem, as long as you don't duplicate them within the field but between fields (but @peterdesmet correct me if I'm wrong).

**Comment by bart-v** [comment]
For WRIMS, we don't have the concept of "a taxon" in the database. So the taxonID is not relevant for us.
If you really need it, please keep on using what is provided (a numeric value, not a GUID)

BTW: scientificNameID is _not_ a unique identifier for the species, but for the **name**!

**Comment by peterdesmet** [comment]
@bart-v here is what I suggest:

1. The `taxonID` in the WRIMS DwC-A is currently populated with the short (integer) form of the AphiaID (e.g. `2`). Can you use the long form AphiaID (`urn:lsid:marinespecies.org:taxname:2`)? Using that it cannot be confused with a random integer and its provenance is clear. Note: obviously this long form should then also be used in the extensions to keep the relations.
2. Technically `urn:lsid:marinespecies.org:taxname:2` is not a [scientificNameID](http://rs.tdwg.org/dwc/terms/index.htm#scientificNameID). As far as I can tell WRIMS doesn't deal with taxon concepts (which would warrant a `taxonConceptID`), but it doesn't purely deal with names either (which would warrant a `scientificNameID`): it provides higher classification, distributions, ... which does not fit the definition "An identifier for the nomenclatural (not taxonomic) details of a scientific name." I would just not populate this field, but nothing will break if it remains there.

---

Regarding generating IDs: `taxonID` is a required field (identifying the record) to link the core with extensions + to allow GBIF to recognize taxa when a checklist is republished. Their scope is limited to the dataset. For most of the checklists we publish under TrIAS, such an record identifier is not present in the source data (e.g. an Excel file, does not apply to WRIMS), so we generate one that is as stable as possible given the source data. The alternative, a running number maintained by the checklist author, would have been worse (reordering/reassigning).

**Comment by bart-v** [comment]
These points make sense.
So yes, using the LSID for both is the best solution, indeed.

**Comment by bart-v** [comment]
This has been implemented and will be available in the next export (2019-04-01)
