### ISSUE TITLE
namePublishedIn

### ISSUE THREAD

**Issue by LienReyserhove** [trias-project/wrims-checklist#6]
just a small remark on the field `namePublishedInID`

After inspection of its content, it appears that most of these values are DOI's. I suggest to replace them by the full link. 

E.g.:

namePublishedInID = 10.1038/nature08742 
**becomes**
namePublishedInID = https://doi.org/10.1038/nature08742

Using these , you are redirected immediately to the correct publication.

**Comment by qgroom** [comment]
Sound good to me.
