### ISSUE TITLE
acceptedNameUsage and scientificName

### ISSUE THREAD

**Issue by LienReyserhove** [trias-project/wrims-checklist#7]
`scientificName` and `acceptedNameUsage` are not the identical for 584 taxa. If I interpret this correctly, then this means that for 584 taxa included in the checklist, the scientificName is outdated. The "problem" is that, in this case, a taxon appears twice in the checklist: once with the outdated scientificName and once with the most recent scientificName (i.e. acceptedNamaUsage).

E.g. for the species `Paracartia grani`:

record | scientificName | acceptedNameUsage 
--- | --- | ---
1 | Acartia grani | Paracartia grani
2 | Paracartia grani | Paracartia grani

Thus, I guess we can remove those records for which `scientificName ` differs from `acceptedNameUsage`, **given that** they are are all repeated as in the example.

Fyi:

AcceptedNameUsage:
> The full name, with authorship and date information if known, of the currently valid (zoological) or accepted (botanical) taxon.

**Comment by bart-v** [comment]
You should merge those records, as i.e. Acartia grani has a distribution attached to it:
http://www.marinespecies.org/introduced/aphia.php?p=taxdetails&id=232027#distributions

**Comment by peterdesmet** [comment]
I assume those 584 names are synonyms? In that case taxonomicStatus should be “synonym” and acceptedNameUsageID should refer to accepted record (did not check).

We won’t postprocess and merge this info: that means that both taxa (with associated info) will be linked to GBIF backbone and merged (sharing same accepted taxon) there based on backbone info. That info is in part based on WORMS.
