### ISSUE TITLE
taxonRank

### ISSUE THREAD

**Issue by LienReyserhove** [trias-project/wrims-checklist#8]
Some taxonRanks are not conform the [GBIF vocabulary](http://rs.gbif.org/vocabulary/gbif/rank_2015-04-24.xml):

- `infraphylum`
- `infraclass`
- `parvorder`

Is there a possibility to match these with the GBIF vocabulary?

and:

- `form ` is an alternative term for `forma`
- `subphylum` is an alternative term from `subdivision`

The former are suggested in the GBIF vocab.

**Comment by bart-v** [comment]
- feel free to match the first 3, we don't have any idea how we would do that...
- there is no rank "form" in WRIMS
- subphylum <> subdivision in Animalia

**Comment by peterdesmet** [comment]
@LienReyserhove if only these ranks don’t match, then that is fine. Will just trigger a non-blocking unknown rank issue.

**Comment by bart-v** [comment]
Actually, we have some WRIMS(Aphia) to DwC mapping in the system.
There we map i.e. "infraphylum" to "subphylum" 

But then you could have twice the same rank in the taxonomic tree...
Again, if GBIF cant' handle that...too bad :)

**Comment by peterdesmet** [comment]
Would keep original ranks then
